name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CMake
      run: sudo apt-get install -y cmake
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello-world-executable
        path: build/hello