name: CMake Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Get the version
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-world-executable-${{ steps.get_version.outputs.VERSION }}
        path: build/hello

    - name: Get Release
      if: startsWith(github.ref, 'refs/tags/')
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./build/hello
        asset_name: hello-world-executable-${{ steps.get_version.outputs.VERSION }}
        asset_content_type: application/octet-stream